<?php if(empty($close)) { $close = ''; } ?>
<option value="" <?php $close_sel = ($close && $close == "00:00:00") ? "selected='selected'" : ""; echo $close_sel; ?>>-- CLOSED --</option>
<option value="09:00" <?php $close_sel = ($close && $close == "09:00:00") ? "selected='selected'" : ""; echo $close_sel; ?>>09:00</option>
<option value="09:30" <?php $close_sel = ($close && $close == "09:30:00") ? "selected='selected'" : ""; echo $close_sel; ?>>09:30</option>
<option value="10:00" <?php $close_sel = ($close && $close == "10:00:00") ? "selected='selected'" : ""; echo $close_sel; ?>>10:00</option>
<option value="10:30" <?php $close_sel = ($close && $close == "10:30:00") ? "selected='selected'" : ""; echo $close_sel; ?>>10:30</option>
<option value="11:00" <?php $close_sel = ($close && $close == "11:00:00") ? "selected='selected'" : ""; echo $close_sel; ?>>11:00</option>
<option value="11:30" <?php $close_sel = ($close && $close == "11:30:00") ? "selected='selected'" : ""; echo $close_sel; ?>>11:30</option>
<option value="12:00" <?php $close_sel = ($close && $close == "12:00:00") ? "selected='selected'" : ""; echo $close_sel; ?>>12:00</option>
<option value="12:30" <?php $close_sel = ($close && $close == "12:30:00") ? "selected='selected'" : ""; echo $close_sel; ?>>12:30</option>
<option value="13:00" <?php $close_sel = ($close && $close == "13:00:00") ? "selected='selected'" : ""; echo $close_sel; ?>>13:00</option>
<option value="13:30" <?php $close_sel = ($close && $close == "13:30:00") ? "selected='selected'" : ""; echo $close_sel; ?>>13:30</option>
<option value="14:00" <?php $close_sel = ($close && $close == "14:00:00") ? "selected='selected'" : ""; echo $close_sel; ?>>14:00</option>
<option value="14:30" <?php $close_sel = ($close && $close == "14:30:00") ? "selected='selected'" : ""; echo $close_sel; ?>>14:30</option>
<option value="15:00" <?php $close_sel = ($close && $close == "15:00:00") ? "selected='selected'" : ""; echo $close_sel; ?>>15:00</option>
<option value="15:30" <?php $close_sel = ($close && $close == "15:30:00") ? "selected='selected'" : ""; echo $close_sel; ?>>15:30</option>
<option value="16:00" <?php $close_sel = ($close && $close == "16:00:00") ? "selected='selected'" : ""; echo $close_sel; ?>>16:00</option>
<option value="16:30" <?php $close_sel = ($close && $close == "16:30:00") ? "selected='selected'" : ""; echo $close_sel; ?>>16:30</option>
<option value="17:00" <?php $close_sel = ($close && $close == "17:00:00") ? "selected='selected'" : ""; echo $close_sel; ?>>17:00</option>
<option value="17:30" <?php $close_sel = ($close && $close == "17:30:00") ? "selected='selected'" : ""; echo $close_sel; ?>>17:30</option>
<option value="18:00" <?php $close_sel = ($close && $close == "18:00:00") ? "selected='selected'" : ""; echo $close_sel; ?>>18:00</option>
<option value="18:30" <?php $close_sel = ($close && $close == "18:30:00") ? "selected='selected'" : ""; echo $close_sel; ?>>18:30</option>
<option value="19:00" <?php $close_sel = ($close && $close == "19:00:00") ? "selected='selected'" : ""; echo $close_sel; ?>>19:00</option>
<option value="19:30" <?php $close_sel = ($close && $close == "19:30:00") ? "selected='selected'" : ""; echo $close_sel; ?>>19:30</option>
<option value="20:00" <?php $close_sel = ($close && $close == "20:00:00") ? "selected='selected'" : ""; echo $close_sel; ?>>20:00</option>
<option value="20:30" <?php $close_sel = ($close && $close == "20:30:00") ? "selected='selected'" : ""; echo $close_sel; ?>>20:30</option>
<option value="21:00" <?php $close_sel = ($close && $close == "21:00:00") ? "selected='selected'" : ""; echo $close_sel; ?>>21:00</option>
<option value="21:30" <?php $close_sel = ($close && $close == "21:30:00") ? "selected='selected'" : ""; echo $close_sel; ?>>21:30</option>
<option value="22:00" <?php $close_sel = ($close && $close == "22:00:00") ? "selected='selected'" : ""; echo $close_sel; ?>>22:00</option>
<option value="22:30" <?php $close_sel = ($close && $close == "22:30:00") ? "selected='selected'" : ""; echo $close_sel; ?>>22:30</option>
<option value="23:00" <?php $close_sel = ($close && $close == "23:00:00") ? "selected='selected'" : ""; echo $close_sel; ?>>23:00</option>
<option value="23:30" <?php $close_sel = ($close && $close == "23:30:00") ? "selected='selected'" : ""; echo $close_sel; ?>>23:30</option>